import { Indicator, IndicatorCategory } from '@/types';

export const CATEGORIES: IndicatorCategory[] = [
  {
    id: 'economy',
    label: 'Economy',
    icon: '📈',
    description: 'GDP, trade, investment, debt & fiscal aggregates — the macro picture of national output',
    color: '#463F3A',
  },
  {
    id: 'govt_spending',
    label: 'Government Spending',
    icon: '🏛️',
    description: 'Central government revenue, expenditure, capital investment & sectoral allocations',
    color: '#6B6461',
  },
  {
    id: 'human',
    label: 'Human Development',
    icon: '🎓',
    description: 'Literacy, school enrollment & education expenditure — the building blocks of human capital',
    color: '#8A817C',
  },
  {
    id: 'health',
    label: 'Health',
    icon: '🏥',
    description: 'Life expectancy, mortality rates, immunisation & healthcare access and expenditure',
    color: '#C97A6A',
  },
  {
    id: 'demographics',
    label: 'Demographics',
    icon: '👥',
    description: 'Population size, growth rate, urbanisation, fertility & age structure',
    color: '#A8A19B',
  },
  {
    id: 'infrastructure',
    label: 'Infrastructure & Technology',
    icon: '⚡',
    description: 'Electricity access, internet penetration & mobile connectivity',
    color: '#5E5652',
  },
  {
    id: 'environment',
    label: 'Environment',
    icon: '🌿',
    description: 'CO₂ emissions, forest cover, renewable energy & access to clean water',
    color: '#BCB8B1',
  },
  {
    id: 'social',
    label: 'Social Equity',
    icon: '⚖️',
    description: 'Poverty rates, inequality, women\'s political representation & gender parity in education',
    color: '#E0AFA0',
  },
  {
    id: 'household',
    label: 'Household & Labour',
    icon: '🏠',
    description: 'Individual consumption, wages, labour participation, employment quality & remittances',
    color: '#D4A898',
  },
];

const WB_SOURCE = {
  name: 'World Bank Open Data',
  url: 'https://data.worldbank.org',
  description: 'World Bank Development Indicators — primary source for cross-country time-series data',
};

const IMF_SOURCE = {
  name: 'IMF World Economic Outlook',
  url: 'https://www.imf.org/en/Publications/WEO',
  description: 'IMF macroeconomic forecasts and historical data',
};

const UN_SOURCE = {
  name: 'UN Population Division',
  url: 'https://population.un.org',
  description: 'United Nations demographic estimates and projections',
};

const WHO_SOURCE = {
  name: 'WHO Global Health Observatory',
  url: 'https://www.who.int/data/gho',
  description: 'World Health Organization health statistics',
};

const UNDP_SOURCE = {
  name: 'UNDP Human Development Reports',
  url: 'https://hdr.undp.org',
  description: 'United Nations Development Programme human development data',
};

export const INDICATORS: Indicator[] = [
  // ── ECONOMY ──────────────────────────────────────────────────────────────
  {
    id: 'gdp_total',
    categoryId: 'economy',
    label: 'GDP (Total)',
    description: 'Gross Domestic Product at current US dollar prices',
    wbCode: 'NY.GDP.MKTP.CD',
    unit: 'Current USD',
    unitShort: 'USD',
    format: 'currency',
    scale: 'billions',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE, IMF_SOURCE],
    chartType: 'area',
  },
  {
    id: 'gdp_growth',
    categoryId: 'economy',
    label: 'GDP Growth Rate',
    description: 'Annual percentage growth rate of GDP at market prices',
    wbCode: 'NY.GDP.MKTP.KD.ZG',
    unit: 'Annual %',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE, IMF_SOURCE],
    chartType: 'bar',
    noCAGR: true,
  },
  {
    id: 'gdp_per_capita',
    categoryId: 'economy',
    label: 'GDP Per Capita',
    description: 'GDP divided by midyear population, at current US dollars',
    wbCode: 'NY.GDP.PCAP.CD',
    unit: 'Current USD',
    unitShort: 'USD',
    format: 'currency',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE],
    chartType: 'area',
  },
  {
    id: 'gni_per_capita',
    categoryId: 'economy',
    label: 'GNI Per Capita (Atlas)',
    description: 'Gross National Income per capita using Atlas method',
    wbCode: 'NY.GNP.PCAP.CD',
    unit: 'Current USD',
    unitShort: 'USD',
    format: 'currency',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE],
    chartType: 'line',
  },
  {
    id: 'inflation',
    categoryId: 'economy',
    label: 'Inflation (CPI)',
    description: 'Consumer price inflation measured as annual percentage change',
    wbCode: 'FP.CPI.TOTL.ZG',
    unit: 'Annual %',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE, IMF_SOURCE],
    chartType: 'line',
    noCAGR: true,
  },
  {
    id: 'unemployment',
    categoryId: 'economy',
    label: 'Unemployment Rate',
    description: 'Share of the labor force that is without work but available for and seeking employment',
    wbCode: 'SL.UEM.TOTL.ZS',
    unit: '% of labor force',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE],
    chartType: 'line',
    noCAGR: true,
  },
  {
    id: 'exports',
    categoryId: 'economy',
    label: 'Exports of Goods & Services',
    description: 'Value of all goods and other market services provided to the rest of the world',
    wbCode: 'NE.EXP.GNFS.CD',
    unit: 'Current USD',
    unitShort: 'USD',
    format: 'currency',
    scale: 'billions',
    availableViews: ['actual', 'yoy', 'pct_gdp'],
    sources: [WB_SOURCE],
    chartType: 'area',
  },
  {
    id: 'imports',
    categoryId: 'economy',
    label: 'Imports of Goods & Services',
    description: 'Value of all goods and other market services received from the rest of the world',
    wbCode: 'NE.IMP.GNFS.CD',
    unit: 'Current USD',
    unitShort: 'USD',
    format: 'currency',
    scale: 'billions',
    availableViews: ['actual', 'yoy', 'pct_gdp'],
    sources: [WB_SOURCE],
    chartType: 'area',
  },
  {
    id: 'fdi',
    categoryId: 'economy',
    label: 'FDI Net Inflows',
    description: 'Foreign direct investment net inflows',
    wbCode: 'BX.KLT.DINV.CD.WD',
    unit: 'Current USD',
    unitShort: 'USD',
    format: 'currency',
    scale: 'billions',
    availableViews: ['actual', 'yoy', 'pct_gdp'],
    sources: [WB_SOURCE],
    chartType: 'bar',
  },
  {
    id: 'fx_reserves',
    categoryId: 'economy',
    label: 'Foreign Exchange Reserves',
    description: 'Total reserves including gold (current US$)',
    wbCode: 'FI.RES.TOTL.CD',
    unit: 'Current USD',
    unitShort: 'USD',
    format: 'currency',
    scale: 'billions',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE, IMF_SOURCE],
    chartType: 'area',
  },
  {
    id: 'govt_debt',
    categoryId: 'economy',
    label: 'Government Debt',
    description: 'Central government debt, total as % of GDP',
    wbCode: 'GC.DOD.TOTL.GD.ZS',
    unit: '% of GDP',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE, IMF_SOURCE],
    chartType: 'line',
  },

  // ── HUMAN DEVELOPMENT ────────────────────────────────────────────────────
  {
    id: 'literacy_rate',
    categoryId: 'human',
    label: 'Adult Literacy Rate',
    description: 'Percentage of people ages 15 and above who can read and write',
    wbCode: 'SE.ADT.LITR.ZS',
    unit: '% of population 15+',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE, UNDP_SOURCE],
    chartType: 'line',
  },
  {
    id: 'school_primary',
    categoryId: 'human',
    label: 'Primary School Enrollment',
    description: 'Gross enrollment ratio in primary education',
    wbCode: 'SE.PRM.ENRR',
    unit: '% gross',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE],
    chartType: 'line',
  },
  {
    id: 'school_secondary',
    categoryId: 'human',
    label: 'Secondary School Enrollment',
    description: 'Gross enrollment ratio in secondary education',
    wbCode: 'SE.SEC.ENRR',
    unit: '% gross',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE],
    chartType: 'line',
  },
  {
    id: 'school_tertiary',
    categoryId: 'human',
    label: 'Tertiary Education Enrollment',
    description: 'Gross enrollment ratio in tertiary education (universities, colleges)',
    wbCode: 'SE.TER.ENRR',
    unit: '% gross',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE],
    chartType: 'line',
  },
  {
    id: 'edu_expenditure',
    categoryId: 'human',
    label: 'Government Education Expenditure',
    description: 'Government expenditure on education as % of GDP',
    wbCode: 'SE.XPD.TOTL.GD.ZS',
    unit: '% of GDP',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual', 'pct_gdp'],
    sources: [WB_SOURCE, UNDP_SOURCE],
    chartType: 'bar',
  },

  // ── HEALTH ───────────────────────────────────────────────────────────────
  {
    id: 'life_expectancy',
    categoryId: 'health',
    label: 'Life Expectancy at Birth',
    description: 'Average number of years a newborn infant would live under current mortality patterns',
    wbCode: 'SP.DYN.LE00.IN',
    unit: 'Years',
    unitShort: 'yrs',
    format: 'number',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE, WHO_SOURCE, UN_SOURCE],
    chartType: 'area',
  },
  {
    id: 'infant_mortality',
    categoryId: 'health',
    label: 'Infant Mortality Rate',
    description: 'Deaths of infants under one year old per 1,000 live births',
    wbCode: 'SP.DYN.IMRT.IN',
    unit: 'Per 1,000 live births',
    unitShort: '/1k births',
    format: 'number',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE, WHO_SOURCE, UN_SOURCE],
    chartType: 'area',
  },
  {
    id: 'under5_mortality',
    categoryId: 'health',
    label: 'Under-5 Mortality Rate',
    description: 'Probability per 1,000 that a newborn baby will die before reaching age 5',
    wbCode: 'SH.DYN.MORT',
    unit: 'Per 1,000 live births',
    unitShort: '/1k births',
    format: 'number',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE, WHO_SOURCE, UN_SOURCE],
    chartType: 'area',
  },
  {
    id: 'maternal_mortality',
    categoryId: 'health',
    label: 'Maternal Mortality Ratio',
    description: 'Number of women who die during pregnancy or childbirth per 100,000 live births',
    wbCode: 'SH.STA.MMRT',
    unit: 'Per 100,000 live births',
    unitShort: '/100k births',
    format: 'number',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE, WHO_SOURCE],
    chartType: 'line',
  },
  {
    id: 'health_expenditure',
    categoryId: 'health',
    label: 'Health Expenditure',
    description: 'Current health expenditure as percentage of GDP',
    wbCode: 'SH.XPD.CHEX.GD.ZS',
    unit: '% of GDP',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual', 'pct_gdp'],
    sources: [WB_SOURCE, WHO_SOURCE],
    chartType: 'bar',
  },
  {
    id: 'physicians',
    categoryId: 'health',
    label: 'Physicians Density',
    description: 'Number of physicians per 1,000 people',
    wbCode: 'SH.MED.PHYS.ZS',
    unit: 'Per 1,000 people',
    unitShort: '/1k',
    format: 'number',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE, WHO_SOURCE],
    chartType: 'line',
  },
  {
    id: 'immunization',
    categoryId: 'health',
    label: 'DTP Immunization Coverage',
    description: 'Percentage of children ages 12-23 months immunized against DTP',
    wbCode: 'SH.IMM.IDPT',
    unit: '% of children 12-23 months',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE, WHO_SOURCE],
    chartType: 'line',
  },

  // ── DEMOGRAPHICS ─────────────────────────────────────────────────────────
  {
    id: 'population',
    categoryId: 'demographics',
    label: 'Total Population',
    description: 'De facto population in a country as of July 1 of the year indicated',
    wbCode: 'SP.POP.TOTL',
    unit: 'People',
    unitShort: 'people',
    format: 'number',
    scale: 'millions',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE, UN_SOURCE],
    chartType: 'area',
  },
  {
    id: 'pop_growth',
    categoryId: 'demographics',
    label: 'Population Growth Rate',
    description: 'Annual population growth rate (percent)',
    wbCode: 'SP.POP.GROW',
    unit: 'Annual %',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE, UN_SOURCE],
    chartType: 'line',
    noCAGR: true,
  },
  {
    id: 'urban_pop',
    categoryId: 'demographics',
    label: 'Urban Population Share',
    description: 'Percentage of total population living in urban areas',
    wbCode: 'SP.URB.TOTL.IN.ZS',
    unit: '% of total population',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE, UN_SOURCE],
    chartType: 'area',
  },
  {
    id: 'fertility',
    categoryId: 'demographics',
    label: 'Fertility Rate',
    description: 'Average number of children born per woman if current age-specific fertility rates persist',
    wbCode: 'SP.DYN.TFRT.IN',
    unit: 'Births per woman',
    unitShort: 'births/woman',
    format: 'number',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE, UN_SOURCE],
    chartType: 'line',
  },
  {
    id: 'dependency_ratio',
    categoryId: 'demographics',
    label: 'Age Dependency Ratio',
    description: 'Ratio of dependents (people < 15 or > 64) to the working-age population (15-64)',
    wbCode: 'SP.POP.DPND',
    unit: '% of working-age population',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE, UN_SOURCE],
    chartType: 'line',
  },

  // ── INFRASTRUCTURE & TECHNOLOGY ──────────────────────────────────────────
  {
    id: 'electricity_access',
    categoryId: 'infrastructure',
    label: 'Access to Electricity',
    description: 'Percentage of population with access to electricity',
    wbCode: 'EG.ELC.ACCS.ZS',
    unit: '% of population',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE],
    chartType: 'area',
  },
  {
    id: 'internet_users',
    categoryId: 'infrastructure',
    label: 'Internet Users',
    description: 'Individuals who have used the Internet in the last 3 months',
    wbCode: 'IT.NET.USER.ZS',
    unit: '% of population',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE],
    chartType: 'area',
  },
  {
    id: 'mobile_subscriptions',
    categoryId: 'infrastructure',
    label: 'Mobile Subscriptions',
    description: 'Mobile cellular telephone subscriptions per 100 people',
    wbCode: 'IT.CEL.SETS.P2',
    unit: 'Per 100 people',
    unitShort: '/100',
    format: 'number',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE],
    chartType: 'area',
  },

  // ── ENVIRONMENT ──────────────────────────────────────────────────────────
  {
    id: 'co2_per_capita',
    categoryId: 'environment',
    label: 'CO₂ Emissions Per Capita',
    description: 'Carbon dioxide emissions from burning fossil fuels (metric tons per capita)',
    wbCode: 'EN.ATM.CO2E.PC',
    unit: 'Metric tons per capita',
    unitShort: 'tCO₂/person',
    format: 'number',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE],
    chartType: 'area',
  },
  {
    id: 'co2_total',
    categoryId: 'environment',
    label: 'CO₂ Emissions (Total)',
    description: 'Total carbon dioxide emissions from burning fossil fuels (kt)',
    wbCode: 'EN.ATM.CO2E.KT',
    unit: 'Kilotons',
    unitShort: 'kt',
    format: 'number',
    scale: 'millions',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE],
    chartType: 'area',
  },
  {
    id: 'forest_area',
    categoryId: 'environment',
    label: 'Forest Area',
    description: 'Land under natural or planted stands of trees of at least 5m in situ (% of land area)',
    wbCode: 'AG.LND.FRST.ZS',
    unit: '% of land area',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE],
    chartType: 'line',
  },
  {
    id: 'renewable_energy',
    categoryId: 'environment',
    label: 'Renewable Energy Share',
    description: 'Renewable energy consumption as % of total final energy consumption',
    wbCode: 'EG.FEC.RNEW.ZS',
    unit: '% of total energy',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE],
    chartType: 'area',
  },
  {
    id: 'clean_water',
    categoryId: 'environment',
    label: 'Access to Safe Water',
    description: 'Population using at least basic drinking water services (% of population)',
    wbCode: 'SH.H2O.BASW.ZS',
    unit: '% of population',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE, WHO_SOURCE],
    chartType: 'area',
  },

  // ── SOCIAL EQUITY ────────────────────────────────────────────────────────
  {
    id: 'poverty_190',
    categoryId: 'social',
    label: 'Extreme Poverty Rate ($2.15/day)',
    description: 'Population living on less than $2.15 a day (2017 PPP)',
    wbCode: 'SI.POV.DDAY',
    unit: '% of population',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE],
    chartType: 'area',
  },
  {
    id: 'gini',
    categoryId: 'social',
    label: 'Gini Coefficient',
    description: 'Measure of income inequality (0 = perfect equality, 100 = perfect inequality)',
    wbCode: 'SI.POV.GINI',
    unit: 'Index (0–100)',
    unitShort: 'index',
    format: 'number',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE],
    chartType: 'line',
  },
  {
    id: 'women_parliament',
    categoryId: 'social',
    label: 'Women in Parliament',
    description: 'Proportion of seats held by women in national parliaments',
    wbCode: 'SG.GEN.PARL.ZS',
    unit: '% of total seats',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE],
    chartType: 'line',
  },
  {
    id: 'gender_parity_edu',
    categoryId: 'social',
    label: 'Gender Parity in Education',
    description: 'Ratio of female to male enrollment in primary and secondary education',
    wbCode: 'SE.ENR.PRSC.FM.ZS',
    unit: 'Ratio (female/male)',
    unitShort: 'ratio',
    format: 'number',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE],
    chartType: 'line',
  },

  // ── GOVERNMENT SPENDING ──────────────────────────────────────────────────
  {
    id: 'govt_expense_pct_gdp',
    categoryId: 'govt_spending',
    label: 'Total Government Expenditure',
    description: 'Central government total expense as a percentage of GDP',
    wbCode: 'GC.XPN.TOTL.GD.ZS',
    unit: '% of GDP',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE, IMF_SOURCE],
    chartType: 'area',
  },
  {
    id: 'govt_revenue_pct_gdp',
    categoryId: 'govt_spending',
    label: 'Government Revenue',
    description: 'Central government revenue excluding grants, as % of GDP',
    wbCode: 'GC.REV.XGRT.GD.ZS',
    unit: '% of GDP',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE, IMF_SOURCE],
    chartType: 'area',
  },
  {
    id: 'govt_tax_revenue',
    categoryId: 'govt_spending',
    label: 'Tax Revenue',
    description: 'Compulsory transfers to central government for public purposes, as % of GDP',
    wbCode: 'GC.TAX.TOTL.GD.ZS',
    unit: '% of GDP',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE, IMF_SOURCE],
    chartType: 'area',
  },
  {
    id: 'govt_military_pct_gdp',
    categoryId: 'govt_spending',
    label: 'Military Expenditure (% GDP)',
    description: 'All current and capital expenditures on the armed forces, as % of GDP',
    wbCode: 'MS.MIL.XPND.GD.ZS',
    unit: '% of GDP',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [
      { name: 'SIPRI via World Bank', url: 'https://data.worldbank.org/indicator/MS.MIL.XPND.GD.ZS', description: 'Stockholm International Peace Research Institute data via World Bank' },
    ],
    chartType: 'line',
  },
  {
    id: 'govt_military_usd',
    categoryId: 'govt_spending',
    label: 'Military Expenditure (USD)',
    description: 'Total military expenditure in current US dollars',
    wbCode: 'MS.MIL.XPND.CD',
    unit: 'Current USD',
    unitShort: 'USD',
    format: 'currency',
    scale: 'billions',
    availableViews: ['actual', 'yoy', 'pct_gdp'],
    sources: [
      { name: 'SIPRI via World Bank', url: 'https://data.worldbank.org/indicator/MS.MIL.XPND.CD', description: 'Stockholm International Peace Research Institute data via World Bank' },
    ],
    chartType: 'area',
  },
  {
    id: 'govt_edu_pct_gdp',
    categoryId: 'govt_spending',
    label: 'Education Expenditure (% GDP)',
    description: 'General government expenditure on education as % of GDP',
    wbCode: 'SE.XPD.TOTL.GD.ZS',
    unit: '% of GDP',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE, UNDP_SOURCE],
    chartType: 'bar',
  },
  {
    id: 'govt_health_pct_gdp',
    categoryId: 'govt_spending',
    label: 'Health Expenditure (% GDP)',
    description: 'Current health expenditure from government sources as % of GDP',
    wbCode: 'SH.XPD.CHEX.GD.ZS',
    unit: '% of GDP',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE, WHO_SOURCE],
    chartType: 'bar',
  },
  {
    id: 'govt_capex',
    categoryId: 'govt_spending',
    label: 'Government Capital Investment',
    description: 'General government gross fixed capital formation (% of GDP) — proxies public infrastructure & investment spending',
    wbCode: 'NE.GDI.GOVT.ZS',
    unit: '% of GDP',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE, IMF_SOURCE],
    chartType: 'area',
    notes: 'Gross fixed capital formation by general government. Includes roads, railways, power, water and other public infrastructure investment.',
  },
  {
    id: 'govt_interest_pct_exp',
    categoryId: 'govt_spending',
    label: 'Interest Payments (% of Expense)',
    description: 'Interest payments as a share of total central government expense — indicates debt-service burden',
    wbCode: 'GC.XPN.INTP.ZS',
    unit: '% of expense',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE, IMF_SOURCE],
    chartType: 'line',
  },
  {
    id: 'govt_subsidies_pct_exp',
    categoryId: 'govt_spending',
    label: 'Subsidies & Transfers (% of Expense)',
    description: 'Subsidies, grants and social benefits as a share of total government expense',
    wbCode: 'GC.XPN.TRFT.ZS',
    unit: '% of expense',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE, IMF_SOURCE],
    chartType: 'area',
  },
  {
    id: 'govt_wages_pct_exp',
    categoryId: 'govt_spending',
    label: 'Compensation of Employees (% of Expense)',
    description: 'Wages and salaries of government employees as a share of total expense',
    wbCode: 'GC.XPN.COMP.ZS',
    unit: '% of expense',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE, IMF_SOURCE],
    chartType: 'area',
  },

  // ── HOUSEHOLD & LABOUR ───────────────────────────────────────────────────
  {
    id: 'household_consumption_pc',
    categoryId: 'household',
    label: 'Household Consumption Per Capita',
    description: 'Real household final consumption expenditure per capita (constant 2015 US$) — measures average purchasing power of individuals',
    wbCode: 'NE.CON.PRVT.PC.KD',
    unit: 'Constant 2015 USD',
    unitShort: 'USD',
    format: 'currency',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE],
    chartType: 'area',
  },
  {
    id: 'household_consumption_growth',
    categoryId: 'household',
    label: 'Household Consumption Growth',
    description: 'Annual growth rate of real household consumption expenditure per capita — how fast living standards are rising',
    wbCode: 'NE.CON.PRVT.PC.KD.ZG',
    unit: 'Annual %',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE],
    chartType: 'bar',
    noCAGR: true,
  },
  {
    id: 'labour_participation',
    categoryId: 'household',
    label: 'Labour Force Participation Rate',
    description: 'Share of population ages 15+ that is economically active (employed or actively seeking work)',
    wbCode: 'SL.TLF.CACT.ZS',
    unit: '% of population 15+',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE],
    chartType: 'line',
  },
  {
    id: 'employment_ratio',
    categoryId: 'household',
    label: 'Employment-to-Population Ratio',
    description: 'Proportion of working-age population (15+) that is employed — a broader measure of labour market health than unemployment',
    wbCode: 'SL.EMP.TOTL.SP.ZS',
    unit: '% of population 15+',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE],
    chartType: 'line',
  },
  {
    id: 'vulnerable_employment',
    categoryId: 'household',
    label: 'Vulnerable Employment',
    description: 'Share of workers in own-account or contributing family work — proxies informal, low-security, low-income employment',
    wbCode: 'SL.EMP.VULN.ZS',
    unit: '% of total employment',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual'],
    sources: [WB_SOURCE],
    chartType: 'area',
  },
  {
    id: 'labour_productivity',
    categoryId: 'household',
    label: 'Labour Productivity',
    description: 'GDP per person employed (constant 2017 PPP $) — measures how much economic output each worker generates',
    wbCode: 'SL.GDP.PCAP.EM.KD',
    unit: 'Constant 2017 PPP USD',
    unitShort: 'USD',
    format: 'currency',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE],
    chartType: 'area',
  },
  {
    id: 'household_consumption_gdp',
    categoryId: 'household',
    label: 'Household Consumption (% of GDP)',
    description: 'Household final consumption as share of GDP — higher values indicate a consumption-driven economy',
    wbCode: 'NE.CON.PRVT.ZS',
    unit: '% of GDP',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual', 'pct_gdp'],
    sources: [WB_SOURCE],
    chartType: 'area',
  },
  {
    id: 'remittances',
    categoryId: 'household',
    label: 'Personal Remittances Received',
    description: 'Inward remittances from overseas workers as % of GDP — India is the world\'s largest remittance recipient',
    wbCode: 'BX.TRF.PWKR.DT.GD.ZS',
    unit: '% of GDP',
    unitShort: '%',
    format: 'percent',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE],
    chartType: 'area',
  },
  {
    id: 'adjusted_nni_pc',
    categoryId: 'household',
    label: 'Adjusted Net National Income Per Capita',
    description: 'GNI minus consumption of fixed capital and natural resource depletion — a more complete measure of true national wealth per person',
    wbCode: 'NY.ADJ.NNTY.PC.CD',
    unit: 'Current USD',
    unitShort: 'USD',
    format: 'currency',
    scale: 'none',
    availableViews: ['actual', 'yoy'],
    sources: [WB_SOURCE],
    chartType: 'area',
  },
];

export function getIndicatorsByCategory(categoryId: string): Indicator[] {
  return INDICATORS.filter((i) => i.categoryId === categoryId);
}

export function getIndicatorById(id: string): Indicator | undefined {
  return INDICATORS.find((i) => i.id === id);
}
